export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";

export const RECENT_CHAT_USERS_REQUEST = "RECENT_CHAT_USERS_REQUEST";
export const GROUPS_SUCCESS = "GROUPS_SUCCESS";

export const CONTACTS_SUCCESS = "CONTACTS_SUCCESS";

export const SELECT_CONTACT = "SELECT_CONTACT";
export const SELECT_GROUP = "SELECT_GROUP";

export const GET_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST";
export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";

