export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const RECENT_CHAT_USERS_REQUEST = "RECENT_CHAT_USERS_REQUEST";
export const RECENT_CHAT_USERS_SUCCESS = "RECENT_CHAT_USERS_SUCCESS";
export const RECENT_CHAT_USERS_ERROR = "RECENT_CHAT_USERS_ERROR";
export const GROUPS_REQUEST = "GROUPS_REQUEST";
export const GROUPS_SUCCESS = "GROUPS_SUCCESS";
export const GROUPS_ERROR = "GROUPS_ERROR";
export const CONTACTS_REQUEST = "CONTACTS_REQUEST";
export const CONTACTS_SUCCESS = "CONTACTS_SUCCESS";
export const CONTACTS_ERROR = "CONTACTS_SUCCESS";

export const SELECT_CONTACT = "SELECT_CONTACT";
export const SELECT_GROUP = "SELECT_GROUP";

export const GET_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_ERROR = "GET_MESSAGE_ERROR";

export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
